In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
from dotenv import load_dotenv
import os
load_dotenv()

True

In [3]:
df = pd.read_csv(os.getenv('csv_path'))

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103024 entries, 0 to 103023
Data columns (total 20 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date                        103024 non-null  object
 1   Time                        103024 non-null  object
 2   Booking_ID                  103024 non-null  object
 3   Booking_Status              103024 non-null  object
 4   Customer_ID                 103024 non-null  object
 5   Vehicle_Type                103024 non-null  object
 6   Pickup_Location             103024 non-null  object
 7   Drop_Location               103024 non-null  object
 8   V_TAT                       63967 non-null   float64
 9   C_TAT                       63967 non-null   float64
 10  Canceled_Rides_by_Customer  10499 non-null   object
 11  Canceled_Rides_by_Driver    18434 non-null   object
 12  Incomplete_Rides            63967 non-null   object
 13  Incomplete_Rides_Reason     3926 non-null    object
 14  Booking_Value               103024 non-null  int64
 15  Payment_Method              63967 non-null   object
 16  Ride_Distance               103024 non-null  int64
 17  Driver_Ratings              63967 non-null   float64
 18  Customer_Rating             63967 non-null   float64
 19  Vehicle Images              103024 non-null  object
dtypes: float64(4), int64(2), object(14)
memory usage: 15.7+ MB

In [5]:
df.isnull().sum()*100/df.shape[0]#103024

Date                           0.000000
Time                           0.000000
Booking_ID                     0.000000
Booking_Status                 0.000000
Customer_ID                    0.000000
Vehicle_Type                   0.000000
Pickup_Location                0.000000
Drop_Location                  0.000000
V_TAT                         37.910584
C_TAT                         37.910584
Canceled_Rides_by_Customer    89.809171
Canceled_Rides_by_Driver      82.107082
Incomplete_Rides              37.910584
Incomplete_Rides_Reason       96.189237
Booking_Value                  0.000000
Payment_Method                37.910584
Ride_Distance                  0.000000
Driver_Ratings                37.910584
Customer_Rating               37.910584
Vehicle Images                 0.000000
dtype: float64

In [6]:
df.duplicated().sum()#no duplicate rows

np.int64(0)

In [7]:
df['Booking_Status'].value_counts()

Booking_Status
Success                 63967
Canceled by Driver      18434
Canceled by Customer    10499
Driver Not Found        10124
Name: count, dtype: int64

In [8]:
df.groupby('Booking_Status')[['Incomplete_Rides']].count()

                      Incomplete_Rides
Booking_Status
Canceled by Customer                 0
Canceled by Driver                   0
Driver Not Found                     0
Success                          63967

In [10]:
df.groupby('Booking_Status')['Payment_Method'].count()

Booking_Status
Canceled by Customer        0
Canceled by Driver          0
Driver Not Found            0
Success                 63967
Name: Payment_Method, dtype: int64

In [11]:
pd.crosstab(df['Booking_Status'], df['Payment_Method'],dropna=False)

Payment_Method         Cash  Credit Card  Debit Card    UPI    NaN
Booking_Status
Canceled by Customer      0            0           0      0  10499
Canceled by Driver        0            0           0      0  18434
Driver Not Found          0            0           0      0  10124
Success               35022         2435         629  25881      0

In [12]:
pd.crosstab(df['Booking_Status'], df['Incomplete_Rides'],dropna=False)

Incomplete_Rides         No   Yes    NaN
Booking_Status
Canceled by Customer      0     0  10499
Canceled by Driver        0     0  18434
Driver Not Found          0     0  10124
Success               60041  3926      0

In [17]:
# for every cancelstatus by driver|customer, there is a response in cancelled_ride_by_driver|customer

In [18]:
df['Incomplete_Rides_Reason'].value_counts(dropna=False)

Incomplete_Rides_Reason
NaN                  99098
Customer Demand       1601
Vehicle Breakdown     1591
Other Issue            734
Name: count, dtype: int64

In [19]:
df['Incomplete_Rides'].value_counts(dropna=False)

Incomplete_Rides
No     60041
NaN    39057
Yes     3926
Name: count, dtype: int64

In [21]:
df[df['Booking_Status']=='Success']['Incomplete_Rides'].count()

np.int64(63967)

In [22]:
df['Vehicle_Type'].value_counts(dropna=False)

Vehicle_Type
Prime Sedan    14877
eBike          14816
Auto           14755
Prime Plus     14707
Bike           14662
Prime SUV      14655
Mini           14552
Name: count, dtype: int64

In [23]:
df[df['Booking_Status']=='Success']['Incomplete_Rides_Reason'].value_counts(dropna=False)

Incomplete_Rides_Reason
NaN                  60041
Customer Demand       1601
Vehicle Breakdown     1591
Other Issue            734
Name: count, dtype: int64

In [24]:
df[df['Booking_Status']=='Canceled by Customer']['Incomplete_Rides_Reason'].value_counts(dropna=False)

Incomplete_Rides_Reason
NaN    10499
Name: count, dtype: int64

In [26]:
df['Canceled_Rides_by_Customer'].value_counts(dropna=False)

Canceled_Rides_by_Customer
NaN                                             92525
Driver is not moving towards pickup location     3175
Driver asked to cancel                           2670
Change of plans                                  2081
AC is Not working                                1568
Wrong Address                                    1005
Name: count, dtype: int64

In [29]:
df.loc[df['Booking_Status']=='Canceled by Customer',['Canceled_Rides_by_Customer','Canceled_Rides_by_Driver']]

                          Canceled_Rides_by_Customer Canceled_Rides_by_Driver
3       Driver is not moving towards pickup location                      NaN
29                            Driver asked to cancel                      NaN
32      Driver is not moving towards pickup location                      NaN
65                                 AC is Not working                      NaN
99                            Driver asked to cancel                      NaN
...                                              ...                      ...
102960  Driver is not moving towards pickup location                      NaN
102977  Driver is not moving towards pickup location                      NaN
102983  Driver is not moving towards pickup location                      NaN
102994                        Driver asked to cancel                      NaN
102999  Driver is not moving towards pickup location                      NaN

[10499 rows x 2 columns]