In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
from dotenv import load_dotenv
import os
load_dotenv()

True

In [3]:
df = pd.read_csv(os.getenv('csv_path'))

In [4]:
df.shape

(103024, 20)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103024 entries, 0 to 103023
Data columns (total 20 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date                        103024 non-null  object
 1   Time                        103024 non-null  object
 2   Booking_ID                  103024 non-null  object
 3   Booking_Status              103024 non-null  object
 4   Customer_ID                 103024 non-null  object
 5   Vehicle_Type                103024 non-null  object
 6   Pickup_Location             103024 non-null  object
 7   Drop_Location               103024 non-null  object
 8   V_TAT                       63967 non-null   float64
 9   C_TAT                       63967 non-null   float64
 10  Canceled_Rides_by_Customer  10499 non-null   object
 11  Canceled_Rides_by_Driver    18434 non-null   object
 12  Incomplete_Rides            63967 non-null   object
 13  Incomplete_Rides_Reason     3926 non-null    object
 14  Booking_Value               103024 non-null  int64
 15  Payment_Method              63967 non-null   object
 16  Ride_Distance               103024 non-null  int64
 17  Driver_Ratings              63967 non-null   float64
 18  Customer_Rating             63967 non-null   float64
 19  Vehicle Images              103024 non-null  object
dtypes: float64(4), int64(2), object(14)
memory usage: 15.7+ MB

In [6]:
df.isnull().sum()*100/df.shape[0]

Date                           0.000000
Time                           0.000000
Booking_ID                     0.000000
Booking_Status                 0.000000
Customer_ID                    0.000000
Vehicle_Type                   0.000000
Pickup_Location                0.000000
Drop_Location                  0.000000
V_TAT                         37.910584
C_TAT                         37.910584
Canceled_Rides_by_Customer    89.809171
Canceled_Rides_by_Driver      82.107082
Incomplete_Rides              37.910584
Incomplete_Rides_Reason       96.189237
Booking_Value                  0.000000
Payment_Method                37.910584
Ride_Distance                  0.000000
Driver_Ratings                37.910584
Customer_Rating               37.910584
Vehicle Images                 0.000000
dtype: float64

In [ ]:
df.drop(columns=['Vehicle Images'], inplace=True)

df['Date'] = pd.to_datetime(df['Date'])

df['TAT_Applicable'] = (df['Booking_Status'] == 'Success').astype(int)
df['Is_Rated_Ride'] = (df['Booking_Status'] == 'Success').astype(int)

df['Payment_Method'] = df['Payment_Method'].fillna('Not Applicable')
df['Incomplete_Rides'] = df['Incomplete_Rides'].fillna('Not Applicable')

df['Incomplete_Rides_Reason'] = df['Incomplete_Rides_Reason'].fillna('Not Applicable')
df.loc[df['Booking_Status'] == 'Success', 'Incomplete_Rides_Reason'] = 'Ride Completed'

df['Canceled_Rides_by_Customer'] = df['Canceled_Rides_by_Customer'].fillna('Not Applicable')
df['Canceled_Rides_by_Driver'] = df['Canceled_Rides_by_Driver'].fillna('Not Applicable')

In [7]:
df.drop(columns=['Vehicle Images'],inplace=True)

In [8]:
df['Date']=pd.to_datetime(df['Date'])

In [9]:
df['Is_Rated_Ride'] = df['Customer_Rating'].notna().astype(int) # rated or not filter col

df['Driver_Ratings'] = df['Driver_Ratings'].fillna(-1)
df['Customer_Rating'] = df['Customer_Rating'].fillna(-1)

In [10]:
df['Payment_Method'] = df['Payment_Method'].fillna('Not Applicable') # fill na payment method

In [11]:
df['TAT_Applicable'] = df['C_TAT'].notna().astype(int) #tat applicable or not , then fill tat with -1 whre not applicable

df['C_TAT']=df['C_TAT'].fillna(-1)
df['V_TAT']=df['V_TAT'].fillna(-1)

In [12]:
df['Incomplete_Rides'] = (df['Incomplete_Rides'].fillna('Not Applicable')) # nan are not booked rides

In [13]:
# filling Incomplete_Rides_Reason nan

df.loc[df['Booking_Status'] == 'Success','Incomplete_Rides_Reason'] = df.loc[df['Booking_Status'] == 'Success','Incomplete_Rides_Reason'].fillna('Ride Complete')

df.loc[df['Booking_Status']=='Canceled by Customer', 'Incomplete_Rides_Reason'] = df.loc[df['Booking_Status']=='Canceled by Customer', 'Incomplete_Rides_Reason'].fillna('Canceled by Customer')

df.loc[df['Booking_Status']=='Canceled by Driver', 'Incomplete_Rides_Reason'] = df.loc[df['Booking_Status']=='Canceled by Driver', 'Incomplete_Rides_Reason'].fillna('Canceled by Driver')

df.loc[df['Booking_Status']=='Driver Not Found', 'Incomplete_Rides_Reason'] = df.loc[df['Booking_Status']=='Driver Not Found', 'Incomplete_Rides_Reason'].fillna('Driver Not Found')

In [14]:
# filling canceled by customer nan

df.loc[df['Booking_Status']=='Success','Canceled_Rides_by_Customer'] = df.loc[df['Booking_Status']=='Success','Canceled_Rides_by_Customer'].fillna('Ride Complete')

df.loc[df['Booking_Status']=='Canceled by Driver','Canceled_Rides_by_Customer'] = df.loc[df['Booking_Status']=='Canceled by Driver','Canceled_Rides_by_Customer'].fillna('Canceled by Driver')

df.loc[df['Booking_Status']=='Driver Not Found','Canceled_Rides_by_Customer'] = df.loc[df['Booking_Status']=='Driver Not Found','Canceled_Rides_by_Customer'].fillna('Driver Not Found')

In [15]:
# filling canceled by driver nan

df.loc[df['Booking_Status']=='Success','Canceled_Rides_by_Driver'] = df.loc[df['Booking_Status']=='Success','Canceled_Rides_by_Driver'].fillna('Ride Complete')

df.loc[df['Booking_Status']=='Canceled by Customer','Canceled_Rides_by_Driver'] = df.loc[df['Booking_Status']=='Canceled by Customer','Canceled_Rides_by_Driver'].fillna('Canceled by Customer')

df.loc[df['Booking_Status']=='Driver Not Found','Canceled_Rides_by_Driver'] = df.loc[df['Booking_Status']=='Driver Not Found','Canceled_Rides_by_Driver'].fillna('Driver Not Found')

In [12]:
pd.crosstab(
    df['Booking_Status'],
    df['Incomplete_Rides'],
    dropna=False
)

Incomplete_Rides         No   Yes    NaN
Booking_Status
Canceled by Customer      0     0  10499
Canceled by Driver        0     0  18434
Driver Not Found          0     0  10124
Success               60041  3926      0

In [11]:
df['Incomplete_Rides'].value_counts(dropna=False)

Incomplete_Rides
No     60041
NaN    39057
Yes     3926
Name: count, dtype: int64

In [20]:
df

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,NaN,Personal & Car related issue,NaN,NaN,444,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/14183/1...
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NaN,NaN,No,NaN,158,Cash,13,4.1,4.0,https://cdn-icons-png.flaticon.com/128/9983/99...
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8,https://cdn-icons-png.flaticon.com/128/9983/99...
3,2024-07-22 03:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,Driver is not moving towards pickup location,NaN,NaN,NaN,384,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/6839/68...
4,2024-07-02 09:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NaN,NaN,No,NaN,822,Credit Card,45,4.0,3.0,https://cdn-icons-png.flaticon.com/128/3202/32...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103019,2024-07-31 09:06:00,09:06:00,CNR9488489435,Success,CID371654,Prime Plus,Richmond Town,Varthur,245.0,35.0,NaN,NaN,No,NaN,111,Cash,41,3.6,3.8,https://cdn-icons-png.flaticon.com/128/11409/1...
103020,2024-07-31 15:12:00,15:12:00,CNR3151743100,Success,CID334158,Auto,Vijayanagar,Richmond Town,84.0,145.0,NaN,NaN,No,NaN,1097,UPI,17,4.3,3.3,https://cdn-icons-png.flaticon.com/128/16526/1...
103021,2024-07-31 13:59:00,13:59:00,CNR1286151233,Success,CID113188,Prime SUV,Bannerghatta Road,JP Nagar,35.0,75.0,NaN,NaN,No,NaN,2201,Cash,37,3.6,3.2,https://cdn-icons-png.flaticon.com/128/9983/99...
103022,2024-07-31 14:56:00,14:56:00,CNR2027162035,Success,CID118301,eBike,Indiranagar,Magadi Road,210.0,140.0,NaN,NaN,No,NaN,267,UPI,47,3.4,3.1,https://cdn-icons-png.flaticon.com/128/6839/68...
103023,2024-07-31 13:57:00,13:57:00,CNR9770709721,Success,CID217959,Auto,Ulsoor,Hennur,175.0,125.0,NaN,NaN,No,NaN,462,UPI,3,4.8,4.4,https://cdn-icons-png.flaticon.com/128/16526/1...

In [6]:
df[df['Booking_Status']=='Canceled by Customer'].shape

(10499, 20)